name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: docker://kivy/buildozer:latest
        with:
          args: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Math-Tools-APK
          path: bin/*.apk
